loaders:
  directory: ./data
  pattern: "*.txt"
chunking:
  chunk_size: 500
  overlap: 50
embedding:
  model: sentence-transformers/all-MiniLM-L6-v2
vector_store:
  type: faiss
  dimension: 384
  metric: cosine
retrieval:
  top_k: 5
  reranker: null
  hybrid: false
llm:
  provider: openai
  model: gpt-3.5-turbo
  temperature: 0.7
