loaders:
  directory: ./docs
  pattern: "*.*"
chunking:
  chunk_size: 500
  overlap: 50
embedding:
  model: text-embedding-3-small
  api_key: ""
  base_url: https://api.siliconflow.cn/v1
vector_store:
  type: faiss
  dimension: 1536
  metric: cosine
retrieval:
  top_k: 5
  reranker: null
  reranker_api_key: ""
  reranker_base_url: https://api.siliconflow.cn/v1/rerank
  hybrid: false
llm:
  provider: openai
  model: gpt-3.5-turbo
  temperature: 0.7
  api_key: ""
  base_url: ""
