chunking:
  chunk_size: 500
  overlap: 50
embedding:
  api_key: ${EMBEDDING_API_KEY}
  base_url: https://api.siliconflow.cn/v1/embeddings
  model: BAAI/bge-m3
llm:
  api_key: ${OPENAI_API_KEY}
  base_url: https://api.deepseek.com/v1
  model: deepseek-chat
  provider: openai
  temperature: 0.7
loaders:
  directory: ./docs
  pattern: '*.PDF'
retrieval:
  hybrid: false
  reranker: BAAI/bge-reranker-v2-m3
  reranker_api_key: ${RERANKER_API_KEY}
  reranker_base_url: https://api.siliconflow.cn/v1/rerank
  top_k: 5
vector_store:
  dimension: 1024
  metric: cosine
  type: faiss
